utils::globalVariables(c("incProgress", "starter.run","observerPool","temp.max.group","temp.val.group",
                         "temp.max.fleet","temp.val.fleet","temp.max.fleet.seas","temp.val.fleet.seas","temp.hide",
                         "starter.msy", "starter.run", "starter.orig","data.msy","data.run","data.orig",
                         "forecast.msy","forecast.run","forecast.orig","control.msy","control.run","control.orig",
                         "output.msy","output.run","output.orig","pars.msy","pars.run","pars.orig",
                         "dir.msy","dir.orig","dir.run","dir.base","age.selex","size.selex","size.reten",
                         "size.mort","comb.selex","comb.dead","comb.retain","comb.Lc","ALK","size.50retain",
                         "disp.Desc","addedTabs","filledTabs","numCols","rel_F_orig","rel_C_orig","rel_F_new",
                         "rel_C_new","aggreg.timeSeries.F","aggreg.timeSeries.DB","aggreg.timeSeries.DN",
                         "aggreg.timeSeries.RB","aggreg.timeSeries.RN","prevGroupAlloc","prevTotalAlloc","sliderResolution",
                         "weightNames","weightScale","lengthNames","lengthScale","baseCatch","newCatch",
                         "msyCatch","projCatch","groups","areaNames","seasonNames","fleetNames",
                         "groupNames","numFutCatchYrs","sleepTime","HasRun","managementLimits",
                         "testChecker","InflDisc.Val","SlopeDisc.Val","triggers","targetValue",
                         "tabTitles","tabValues","showInitTab","targetNames","targetNames2","targetNames3",
                         "AppliedKobeBMSY", "AppliedKobeFMSY", "AppliedKobeMSY", "AppliedKobeSSBMSY",
                         "actionBttn", "bsModal", "click", "control.new",
                         "data.new", "dir.outputs", "forecast.new", "foreinput", "hidden", "hideElement",
                         "outfile", "rel_DB_orig", "rel_DN_orig", "rel_RB_orig", "rel_RN_orig", "showElement",
                         "sliderTextInput", "starter.new", "useShinyjs"))
